services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
    networks:
      - webapp-network
    volumes:
      - mongodb_data:/data/db

  webapp-2:
    image: webapp-2:latest
    container_name: webapp-2
    ports:
      - "8080:8080"
    environment:
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=password123
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge

volumes:
  mongodb_data: